# Generated by Django 4.2.7 on 2023-12-12 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_ip_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="social_account",
        ),
    ]
